from . import teslimat_planlama
from . import res_partner
from . import stock_picking
from . import teslimat_arac
from . import teslimat_gun
from . import teslimat_ilce
from . import teslimat_program_kurulum
from . import teslimat_belgesi
from . import teslimat_kapasite_onay
from . import teslimat_planlama_akilli
from . import teslimat_ana_sayfa
